#pragma once

struct ProcessHandleInput
{
	ULONG ProcessId;
};

struct ProcessHandleOutput
{
	HANDLE hProcess;
};

#define PROCHANDLE_DEVICE_IOCTL  0x8301

#define GET_PROCESS_HANDLE_IOCTL  0x820
#define UNKNOWN_FUNC_IOCTL        0x821

#define IOCTL_OPEN_PROCESS CTL_CODE(PROCHANDLE_DEVICE_IOCTL, GET_PROCESS_HANDLE_IOCTL, METHOD_BUFFERED, FILE_ANY_ACCESS)